### ISSUE TITLE
TActor is missing 13 bytes worth of data between `linkedActor` and `positionMirror2`

### ISSUE THREAD

**Issue by Akira13641** [zestydevy/dinosaur-planet#33]
With the struct defined as it is currently, my memory dumping script (which matches the C header exactly) prints output that looks like the following, for example:

```json
"TActor_0": {
  "name": "Krystal",
  "address": "0x806ED020",
  "fields": {
    "rotation": [-25166, 0, 0],
    "unk0x6": 2,
    "scale": 0.0494999997317791,
    "position": [2108.28564453125, -41.19002151489258, 16808.6328125],
    "positionMirror": [2108.28564453125, -41.19002151489258, 16808.6328125],
    "speed": [0, 0, 0],
    "ptr0x30": "0x00000000",
    "unk0x34": 65535,
    "linkedActor": "0x800EC398",
    "unk0x3c": [68, 255, 0],
    "unk0x44": 68,
    "unk0x46": 18432,
    "ptr0x48": "0x00000100",
    "unk0x4c": 520094208,
    "ptr0x50": "0x00000000",
    "ptr0x54": "0x00803981",
    "unk0x58": 3900731102,
    "ptr0x5c": "0x7C000000",
    "ptr0x60": "0x00806286",
    "ptr0x64": "0x08806ED9",
    "ptr0x68": "0xD8806EDE",
    "ptr0x6c": "0x38802529",
    "ptr0x70": "0xD0806EDF",
    "unk0x74": 545287903,
    "positionMirror2": [-2199023255552, 0, 1.1794696944357306e-38],
    "positionMirror3": [2.3158967801400164e-36, -1.2252182749418445e-27, -4.008937194294739e-26],
```

however, since `positionMirror2` and `positionMirror3` are actually always the same as `position` and `positionMirror` when the game is running, clearly that's not correct output. Looking into it in the debugger, I realized that the actual amount of space between `linkedActor` and `positionMirror2` in practice is 68 bytes (or 44 if using hex format values, as shown in the image I've attached) whereas the C header definition currently only adds up to 55 bytes across the following section:

```C
u8 unk0x3c[3];
UNK_TYPE_16 unk0x44;
UNK_TYPE_16 unk0x46;
void* ptr0x48;
UNK_TYPE_32 unk0x4c;
void* ptr0x50;
void* ptr0x54;
UNK_TYPE_32 unk0x58;
void* ptr0x5c;
void* ptr0x60;
void* ptr0x64;
void* ptr0x68;
void* ptr0x6c;
void* ptr0x70;
UNK_TYPE_32 unk0x74;
```

After adjusting my script to reflect what I was actually seeing in memory, it then produced output that looks like this, which has the correct values for `positionMirror2` and `positionMirror3`, as well as what look to me like more meaningful values for the surrounding fields:

```json
"TActor_0": {
  "name": "Krystal",
  "address": "0x806ED020",
  "fields": {
    "rotation": [-25166, 0, 0],
    "unk0x6": 2,
    "scale": 0.0494999997317791,
    "position": [2108.28564453125, -41.19002151489258, 16808.6328125],
    "positionMirror": [2108.28564453125, -41.19002151489258, 16808.6328125],
    "speed": [0, 0, 0],
    "ptr0x30": "0x00000000",
    "unk0x34": 65535,
    "linkedActor": "0x800EC398",
    "unk0x3c": 17663,
    "unk0x3e": 0,
    "unk0x40": 17480,
    "unk0x42": 0,
    "unk0x44": 65567,
    "unk0x48": 131072,
    "ptr0x4c": "0x00000000",
    "ptr0x50": "0x803981E8",
    "ptr0x54": "0x806EDE7C",
    "ptr0x58": "0x00000000",
    "ptr0x5c": "0x80628608",
    "ptr0x60": "0x806ED9D8",
    "ptr0x64": "0x806EDE38",
    "ptr0x68": "0x802529D0",
    "ptr0x6c": "0x806EDF20",
    "ptr0x70": "0x806EDFD4",
    "ptr0x74": "0x00000000",
    "ptr0x78": "0x00000000",
    "ptr0x7c": "0x806ED104",
    "positionMirror2": [2108.28564453125, -41.19002151489258, 16808.6328125],
    "positionMirror3": [2108.28564453125, -41.19002151489258, 16808.6328125],
```

If you want, I can make a PR that updates the C header definition with the same adjustments I did for my script. Figured I'd open an issue for it first though as there was a fair amount of background info that needed explaining.

![DebugView](https://user-images.githubusercontent.com/11223712/109873901-68056c80-7c3c-11eb-9453-77668851c2ff.png)

**Comment by Sunlitspace542** [comment]
As long as your changes compile into a matching ROM, I can't see why you shouldnt be able to just make a pr

**Comment by Akira13641** [comment]
I'm not able to test that locally at the moment, but presumably that's something that's verified by the auto-build / auto-test process upon receiving a PR, right?

I will note though that there's a comment above the TActor struct that calls it preliminary and says it "might be bigger", which also makes me think that maybe it's intentionally not yet being "validated" at all.

**Comment by wedarobi** [comment]
> As long as your changes compile into a matching ROM, I can't see why you shouldnt be able to just make a PR

Because it's good practice and helpful to open issues when theres confusion, instead of submitting a potentially problematic PR.

**Comment by slightlyoutofphase** [comment]
Ok, upon searching, it [does not appear](https://github.com/zestydevy/dinosaur-planet/search?q=tactor) that any direct non-pointer uses of `TActor` actually exist in C code anywhere in the repo. Therefore I think technically you could define it as a completely empty struct for example, and the generated code still wouldn't change. 

So any change I make will moreso amount to just more closely matching what the game actually has in memory while running, which would need to be done at some point later anyways whenever someone actually went to write non-trivial code using `TActor`.

**Comment by Akira13641** [comment]
Ok, upon searching, it [does not appear](https://github.com/zestydevy/dinosaur-planet/search?q=tactor) that any direct non-pointer uses of `TActor` actually exist in C code anywhere in the repo. Therefore I think technically you could define it as a completely empty struct for example, and the generated code still wouldn't change. 

So any change I make will moreso amount to just more closely matching what the game actually has in memory while running, which would need to be done at some point later anyways whenever someone actually went to write non-trivial code using `TActor`.

**Comment by Akira13641** [comment]
Here's a comparison showing the equivalent of the changes I'm now using in my memory dump script, to make it produce the correct output: https://github.com/zestydevy/dinosaur-planet/compare/master...Akira13641:master

**Comment by Sunlitspace542** [comment]
well I tried compiling with the changes you made and it does appear to match, I get an OK from the command line after building

**Comment by Akira13641** [comment]
Yeah, like I said, I do believe it would match no matter what currently because the struct is not actually used in C code in a non-pointer context.

**Comment by Akira13641** [comment]
Didn't mean to do that, was working on a comment that I'll have to rewrite now...

**Comment by Akira13641** [comment]
Ok, after navigating to the addresses of various TActors while the game is running for a bunch of hours, I'm extremely confident that [what can be seen here](https://github.com/zestydevy/dinosaur-planet/compare/master...Akira13641:master) is significantly closer to the struct definition as it would have been originally written by Rare.

Running my memory dump script with a layout equivalent to the C one I just linked produces output that looks like this, for example:

```json
"TActor_0": {
  "name": "Krystal",
  "address": "0x806ED020",
  "fields": {
    "rotation": [-19682, 0, 0],
    "unk0x6": 2,
    "scale": 0.0494999997317791,
    "position": [3490.5166015625, -52, 17062.337890625],
    "positionMirror": [3490.5166015625, -52, 17062.337890625],
    "speed": [0, 0, 0],
    "ptr0x30": "0x00000000",
    "unk0x34": 65535,
    "linkedActor": "0x80105458",
    "unk0x3c": 17663,
    "unk0x3e": 0,
    "unk0x40": 17480,
    "unk0x42": 0,
    "unk0x44": 65567,
    "unk0x48": 131072,
    "ptr0x4c": "0x00000000",
    "ptr0x50": "0x803981E8",
    "ptr0x54": "0x806EDE7C",
    "ptr0x58": "0x00000000",
    "ptr0x5c": "0x80628680",
    "ptr0x60": "0x806ED9D8",
    "ptr0x64": "0x806EDE38",
    "ptr0x68": "0x802529D0",
    "ptr0x6c": "0x806EDF20",
    "ptr0x70": "0x806EDFD4",
    "ptr0x74": "0x00000000",
    "ptr0x78": "0x00000000",
    "ptr0x7c": "0x806ED104",
    "positionMirror2": [3490.5166015625, -52, 17062.337890625],
    "positionMirror3": [3490.5166015625, -52, 17062.337890625],
    "unk0x98": 0.27619266510009766,
    "unk0x9c": 0.7937493920326233,
    "someColor1": [4, 48, 255, 255],
    "someVector": [2587.76513671875, 35.19449996948242, -1.7045272127198132e+38],
    "someColor2": [0, 17, 255, 255],
    "someColor3": [255, 255, 0, 0],
    "CharData": {
      "BaseAddress": "0x806ED114",
      "RealAddress": "0x805C3970",
      "fields": {
        "unk0x0": 0,
        "HPCurr": 124,
        "HPMax": 12,
        "unk0x3": 0,
        "ManaCurr": 25,
        "ManaMax": 25,
        "Scarabs": 0,
        "unk0xa": 0,
        "unk0xb": 0
      }
    },
    "ptr0xbc": "0x8060DBC0",
    "ptr0xc0": "0x00000000",
    "ptr0xc4": "0x00000000",
    "uniqueWeapon": "0x800FD100",
    "ptr0xcc": "0x800F5550"
  }
},
```

or for the Cape Claw GuardClaw:

```json
"TActor_14": {
  "name": "GuardClaw",
  "address": "0x803A0DF8",
  "fields": {
    "rotation": [0, 0, 0],
    "unk0x6": 2,
    "scale": 0.10000000149011612,
    "position": [3749.3310546875, -89.08308410644531, 17678.498046875],
    "positionMirror": [3749.3310546875, -89.08308410644531, 17678.498046875],
    "speed": [0, 0, 0],
    "ptr0x30": "0x00000000",
    "unk0x34": 65535,
    "linkedActor": "0x800FD7A8",
    "unk0x3c": 16768,
    "unk0x3e": 0,
    "unk0x40": 17663,
    "unk0x42": 0,
    "unk0x44": 1900760,
    "unk0x48": 1245184,
    "ptr0x4c": "0x805DF624",
    "ptr0x50": "0x800FB448",
    "ptr0x54": "0x803A1350",
    "ptr0x58": "0x00000000",
    "ptr0x5c": "0x00000000",
    "ptr0x60": "0x803A12F4",
    "ptr0x64": "0x00000000",
    "ptr0x68": "0x80252A10",
    "ptr0x6c": "0x803A13F4",
    "ptr0x70": "0x803A1450",
    "ptr0x74": "0x803A14B0",
    "ptr0x78": "0x803A15F4",
    "ptr0x7c": "0x803A0EDC",
    "positionMirror2": [3749.3310546875, -89.08308410644531, 17678.498046875],
    "positionMirror3": [3749.3310546875, -89.08308410644531, 17678.498046875],
    "unk0x98": 0.5099999904632568,
    "unk0x9c": 0,
    "someColor1": [0, 4, 255, 255],
    "someVector": [3022.26806640625, 73.5, 1.6982098755070353e-21],
    "someColor2": [0, 16, 1, 17],
    "someColor3": [255, 255, 0, 0],
    "ptr0xbc": "0x806796C8",
    "ptr0xc0": "0x00000000",
    "ptr0xc4": "0x00000000",
    "uniqueWeapon": "0x00000000",
    "ptr0xcc": "0x800EE5F0"
  }
},
```
